server:
  applicationConnectors:
    - type: http
      port: 5904
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
  adminConnectors:
    - type: http
      port: 5905

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    acacia: DEBUG

  appenders:
    - type: console
    - type: file
      threshold: WARN
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/acacia.log
      archivedLogFilenamePattern: ./logs/acacia-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 10MB
      
ontology:
  file: resources/ontology.owl
